// <auto-generated />
using System;
using EntrenaTuOposicionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntrenaTuOposicionAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514100650_AñadirTablaTemariosReal")]
    partial class AñadirTablaTemariosReal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Oposicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Oposiciones");
                });

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Temario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OposicionId")
                        .HasColumnType("integer");

                    b.Property<bool>("ProcesadoIA")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OposicionId");

                    b.ToTable("Temarios");
                });

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Creditos")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OposicionActivaId")
                        .HasColumnType("integer");

                    b.Property<string>("OposicionActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Oposicion", b =>
                {
                    b.HasOne("EntrenaTuOposicionAPI.Models.Usuario", "Usuario")
                        .WithMany("Oposiciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Temario", b =>
                {
                    b.HasOne("EntrenaTuOposicionAPI.Models.Oposicion", "Oposicion")
                        .WithMany("Temarios")
                        .HasForeignKey("OposicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oposicion");
                });

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Oposicion", b =>
                {
                    b.Navigation("Temarios");
                });

            modelBuilder.Entity("EntrenaTuOposicionAPI.Models.Usuario", b =>
                {
                    b.Navigation("Oposiciones");
                });
#pragma warning restore 612, 618
        }
    }
}
