name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Publicar backend
        run: |

          cd backend/entrenatuoposicionAPI

          dotnet publish -c Release -o publish

      - name: Reiniciar API
        run: |

          sudo systemctl restart entrenatuoposicion